# Generated by Django 4.2.7 on 2023-12-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Images/'),
        ),
    ]
