# Generated by Django 4.2 on 2023-12-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('foster', 'Foster'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn')], max_length=50),
        ),
    ]
