# Generated by Django 4.2.6 on 2023-12-05 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_seeker_user_alter_shelter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('content', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='accounts.shelter')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
