# Generated by Django 4.2.7 on 2023-11-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='url2',
            field=models.URLField(default=''),
        ),
    ]
