# Generated by Django 4.2.7 on 2023-12-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_url1_notification_url2'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
