# Generated by Django 4.2.6 on 2023-11-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_seeker_user_alter_shelter_user'),
        ('pets', '__first__'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
