# Generated by Django 4.2.6 on 2023-11-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_applications_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='updation_date',
            new_name='updation_time',
        ),
    ]
