# Generated by Django 4.2 on 2023-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='list_of_pets',
            field=models.TextField(blank=True),
        ),
    ]
