# Generated by Django 4.2 on 2023-11-12 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_seeker_user_alter_shelter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='list_of_pets',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
