# Generated by Django 4.2 on 2023-11-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_shelter_list_of_pets_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
