# Generated by Django 4.2 on 2023-11-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seeker_avatar_shelter_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar/'),
        ),
    ]
