# Generated by Django 4.2 on 2023-11-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_seeker_avatar_alter_shelter_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeker',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar/'),
        ),
    ]
