# Generated by Django 4.2 on 2023-12-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_seeker_avatar_remove_shelter_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='checking',
            field=models.BooleanField(default=False),
        ),
    ]
