# Generated by Django 4.2.6 on 2023-11-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_options_comments_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created']},
        ),
    ]
