# Generated by Django 4.2.6 on 2023-12-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comments_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.ImageField(default=5, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
