# Generated by Django 4.2 on 2023-12-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comments_rating_alter_comments_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
